sudo: required

language: minimal

services: docker

before_install:
  - docker -v

install:
  - travis_retry docker-compose pull
  - docker build -t digirati/nlw-madoc .

before_script:
  - docker-compose up -d
  - ./.travis/wait-for-omeka.sh

script:
  - .travis/test-script.sh

after_script:
  - docker-compose down

cache:
  bundler: true
  directories:
    - $HOME/docker

deploy:
  # Publishing tags
  - provider: script
    script: bash ./.travis/docker-deploy.sh digirati/nlw-madoc
    on:
      tags: true

if: |
  branch = master OR \
  type = pull_request OR \
  tag IS present
